### PR TITLE
Add Bitmap support in Java

### PR DESCRIPTION
**Pull request by flyingzhao**
Now ,you can pass Bitmap as input instead of image path.It is more flexible than image path. Meanwhile,I add corresponding JNI support in dlib-android. Please check!

### CODE REVIEW

**Comment by tzutalin** [comment]
HI @flyingzhao ,
 Thank you. :) But there are some errors for Travis CI. I will take a look at your code to fix the error first.

**Comment by flyingzhao** [comment]
i am sorry.i don't know how to use travis ci.please look at code.thx

**Comment by tzutalin** [comment]
@flyingzhao 
It's alright. I will look at the code.

**Comment by flyingzhao** [comment]
I miss to import the Bitmap package.Now it is OK.

**Pull request merged**
