### PR TITLE
Using ArrayList<Point> as landmarks container

### PR DESCRIPTION
**Pull request by beraldofilippo**
Please be careful, my configuration was completely different from the one in jnilib_ex, therefore I've added the working version of jni_people_det.cpp into JNIsources folder.

You should be ok in putting that into jnilib_ex (in dlib-android repo), compile and put the new .so files back into jniLibs folder of this repo.

### CODE REVIEW

**Comment by tzutalin** [comment]
HI @beraldofilippo ,  
  Thank you. It is smart and nice to add a new method to add landmark in jni, could I move the code to dlib-android instead of building cpp source in dlib-android-app? I will like to separate the cpp and java code.  Besides, I will like to keep mLabel in VisionDetRet because mLabel field will be used for object detection.
So I would like to merge the commits, d5c12ca and c71f8ed, first, and change it a little bit. Does it sound to you?

**Comment by beraldofilippo** [comment]
Hey @tzutalin sure, my intention was to use the .cpp source in dlib-android and then take the .so files here, just as you did until now! I've put it here just because I didn't have the correct config to build it...

As for the other stuff, yes it should be OK to put back the label filed! I din't think about it because I was concentrating too much on the facial features :P

**Comment by tzutalin** [comment]
Hi @beraldofilippo ,
 I sync your code manually, and change a little bit. I also sync the prebuilt shared library from dlib-android.
https://github.com/tzutalin/dlib-android-app/commit/650afb63f611f775280117fb091714f91b4897ba

**Comment by beraldofilippo** [comment]
Great :D. Shall we close this PR now?

**Comment by tzutalin** [comment]
OK. Thanks for your pull-request

**Pull request closed without merging**
